env:
  browser: true
  es6: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  {
    "quotes": [2, "double"],
    "linebreak-style": 0,
    "comma-dangle": 0,
    "import/prefer-default-export": 0,
    "arrow-parens": 0,
    "arrow-body-style": 0,
    "consistent-return": 0,
    "func-names": 0,
    "space-before-function-paren": 0,
    "implicit-arrow-linebreak": 0,
    "no-confusing-arrow": 0,
    "function-paren-newline": 0,
    "operator-linebreak": 0,
    "nonblock-statement-body-position": 0,
    "curly": 0,
    "no-nested-ternary": 0,
    "indent": 0,
  }
